# O primeiro projeto

## Aula 01 - Introdução à classificação

Previsão com algoritmos de classificação:
1. features
2. itens
3. treino
4. teste
5. taxa de acerto (medida)
6. otimizar
7. prever
- python + sklearn + numpy + graphviz + seaborn

### Primeiro treino e teste de um modelo de classificação

In [1]:
# features (1 sim, 0 não)
# pêlo longo?
# perna curta?
# faz auau?
porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]

# representacao (1 => porco, 0  => cachorro)
dados = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
classes = [1, 1, 1, 0, 0, 0]


# biblioteca sklearn
[Scikit Learn](https://scikit-learn.org/stable/supervised_learning.html#supervised-learning)

In [10]:
# classe linearSVC permite criar o modelo
from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(dados, classes)

LinearSVC()

In [11]:
animal_misterioso = [1, 1, 1]
model.predict([animal_misterioso])

array([0])

In [14]:
misterio1 = [1, 1, 1]
misterio2 = [1, 1, 0]
misterio3 = [0, 1, 1]

testes = [misterio1, misterio2, misterio3]
previsoes = model.predict(testes)

In [15]:
testes_classes = [0, 1, 1]

In [16]:
previsoes

array([0, 1, 0])

In [17]:
testes_classes

[0, 1, 1]

In [20]:
previsoes == testes_classes

array([ True,  True, False])

In [22]:
corretos = (previsoes == testes_classes).sum()
corretos

2

In [23]:
total = len(testes)

In [27]:
taxa_acerto = corretos / total
print(f"Taxa de acertos: {taxa_acerto * 100}")

Taxa de acertos: 66.66666666666666


In [28]:
# MEDINDO A NOTA DE ACERTO
from sklearn.metrics import accuracy_score

taxa_de_acerto = accuracy_score(testes_classes, previsoes)
print('taxa de acerto', taxa_acerto * 100)

taxa de acerto 66.66666666666666
