# O primeiro projeto

## Aula 01 - Introdução à classificação

Previsão com algoritmos de classificação:
1. features
2. itens
3. treino
4. teste
5. taxa de acerto (medida)
6. otimizar
7. prever
- python + sklearn + numpy + graphviz + seaborn

### Primeiro treino e teste de um modelo de classificação

In [44]:
# features (1 sim, 0 não)
# pêlo longo?
# perna curta?
# faz auau?
porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

cachorro1 = [0, 1, 1]
cachorro2 = [1, 0, 1]
cachorro3 = [1, 1, 1]

# representacao (1 => porco, 0  => cachorro)
# f(x) = y
treino_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
treino_y = [1, 1, 1, 0, 0, 0] #labels / etiqueta

# biblioteca sklearn
[Scikit Learn](https://scikit-learn.org/stable/supervised_learning.html#supervised-learning)

In [45]:
# classe linearSVC permite criar o modelo
from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(treino_x, treino_y)

LinearSVC()

In [46]:
animal_misterioso = [1, 1, 1]
model.predict([animal_misterioso])

array([0])

In [47]:
misterio1 = [1, 1, 1]
misterio2 = [1, 1, 0]
misterio3 = [0, 1, 1]

teste_x = [misterio1, misterio2, misterio3]
testes_y = [0, 1, 1]

In [48]:
previsoes = model.predict(teste_x)

In [49]:
previsoes

array([0, 1, 0])

In [50]:
testes_y

[0, 1, 1]

In [51]:
previsoes == testes_y

array([ True,  True, False])

In [52]:
corretos = (previsoes == testes_y).sum()
corretos

2

In [53]:
total = len(teste_x)

In [58]:
taxa_acerto = corretos / total
print(f"Taxa de acertos: {(taxa_acerto * 100):.2f}")

Taxa de acertos: 66.67


In [61]:
# MEDINDO A NOTA DE ACERTO
from sklearn.metrics import accuracy_score

taxa_de_acerto = accuracy_score(testes_y, previsoes)
print('taxa de acerto %.2f' % (taxa_acerto * 100))

taxa de acerto 66.67
